### ISSUE TITLE
Cleaner documentation about color customization

### ISSUE THREAD

**Issue by Toasterson** [okkur/syna#750]
feature

I would like to customize the Button color but the documentation only goes as far as saying that it is possible in config.toml but not how.

I would like to have the documentation section under https://about.okkur.org/syna/docs/development/#styles with two three examples. However I would first need to know how that looks like.

My best assumption below did not help
```toml
[assets]
    [styles]
        [bootstrap]
            danger = "#ff7149"
```
