### ISSUE TITLE
Multi-lingual site shows both languages at the same time in nav and footer

### ISSUE THREAD

**Issue by schoettl** [okkur/syna#792]
**BUG REPORT**

**What happened**:
- I'm trying to get multi-lingual site working.
- I only changed the `config.toml` according to the doc.
- I'm using latest master of syna and syna-starter

In the default language, the menu (and footer as well) shows both translations:

![test](https://user-images.githubusercontent.com/1301843/86508100-a3197c80-bddd-11ea-87a4-6e5720ec39a5.png)

**What you expected to happen**:

Only items of one language should be visible.

**How to reproduce it (as minimally and precisely as possible)**:

See https://github.com/schoettl/syna-start/commit/e13e458586ed5efed2d15bb1507f71e061ab27b6
(one commit based on syna-starter)

**Environment**:
- Syna Theme version:  latest master >= v0.17.2
- Hugo version:  0.73.0

**Comment by mpourismaiel** [comment]
@stp-ip What do you think? Should we remove current language button or implement it in some other way?

**Comment by schoettl** [comment]
Oh, I hope it is not a misunderstanding:

I'm fine with the two language selector buttons "en" and "de".

The problem is that both translations "Home" and "Zuhause" are visible. In the default language "en", there should only be "Home", "About Us", "Contact".

**Comment by mpourismaiel** [comment]
Oh I didn't see that. Thanks for reporting it. I'll get right on it.

**Comment by mpourismaiel** [comment]
Not sure why this happens. Also I'm not sure about the syntax you're using. Seems like the method described in the [Menus section of Multilingual Mode documentation](https://gohugo.io/content-management/multilingual/#menus) uses a different syntax that works with Syna. To clarify, I mean using this syntax:

```toml
[languages.en]
  weight = 0
  languageName = "English"

[[languages.en.menu.main]]
  url    = "/"
  name   = "Home"
  weight = 0


[languages.de]
  weight = 10
  languageName = "Deutsch"

[[languages.de.menu.main]]
  url    = "/"
  name   = "Startseite"
  weight = 0
```
